// English content — translated from the Ampliq Company Profile 2026.
// Keep the same structure as ar.mjs; the build stops if the two differ.

export default {
  lang: "en",
  dir: "ltr",
  locale: "en_US",
  dateLocale: "en-GB",
  brand: "Ampliq",

  ui: {
    skip: "Skip to content",
    menu: "Menu",
    close: "Close menu",
    mainNav: "Main navigation",
    breadcrumb: "Breadcrumb",
    home: "Home",
    switchShort: "عربي",
    switchLabel: "العربية",
    switchAria: "View this page in Arabic",
    contactCta: "Contact us",
    bookCta: "Book a consultation",
    servicesCta: "Explore our services",
    details: "Details",
    readArticle: "Read article",
    allArticles: "All articles",
    backToTop: "Back to top",
    logoAlt: "Ampliq — Amplify Your Business Impact",
    tagline: "AMPLIFY YOUR BUSINESS IMPACT",
    bestFor: "Best for:",
    readTime: (n) => `${n} min read`,
    by: "Ampliq team",
    published: "Published",
    updated: "Last updated",
    toc: "In this article",
    share: "Share this article",
    copyLink: "Copy link",
    copied: "Link copied",
    related: "Related articles",
    faqTitle: "Frequently asked questions",
    moreTitle: "You may also like",
    whatsapp: "Chat on WhatsApp",
    whatsappMessage: "Hello Ampliq, I'm contacting you from this page:",
    cookieText: "We use cookies to measure and improve site traffic, and only switch them on with your consent.",
    cookieAccept: "Accept",
    cookieReject: "Decline",
    cookieMore: "Privacy policy",
  },

  nav: [
    { key: "about", label: "About" },
    { key: "services", label: "Services" },
    { key: "clients", label: "Clients" },
    { key: "blog", label: "Blog" },
  ],

  footer: {
    about: "Ampliq is a Riyadh-based Saudi group specializing in digital marketing, human resources management, and web & software development.",
    company: "Company",
    services: "Services",
    contact: "Contact",
    rights: "All rights reserved.",
    privacy: "Privacy policy",
    terms: "Terms of use",
  },

  cta: {
    title: "Don’t just be seen.",
    accent: "Amplify your impact.",
    text: "Let’s create a bigger impact together. Tell us about your goal, and we’ll suggest the right track and engagement model for your organization.",
  },

  contact: {
    location: "Riyadh, Saudi Arabia",
    labels: { phone: "Phone", email: "Email", whatsapp: "WhatsApp", location: "Location" },
    placeholders: { phone: "[Phone number]", email: "[Email address]", whatsapp: "[WhatsApp number]" },
    steps: {
      title: "What happens next?",
      items: [
        { title: "We understand your goal", text: "We review your request and get in touch to understand your goal and current situation." },
        { title: "We suggest a track", text: "We define the service, engagement model and scope that fit your organization." },
        { title: "We start and measure", text: "We agree on deliverables and KPIs, then start delivery." },
      ],
    },
  },

  form: {
    title: "Send us your request",
    intro: "Fields marked * are required.",
    name: "Full name",
    namePh: "e.g. Sarah Ahmed",
    mobile: "Mobile number",
    mobilePh: "05XXXXXXXX",
    email: "Email",
    emailPh: "name@company.com",
    company: "Organization",
    companyPh: "Optional",
    service: "Service of interest",
    serviceOptions: ["Digital marketing", "Human resources management", "Web & software development", "More than one service", "Not sure yet"],
    budget: "Approximate budget",
    budgetOptions: ["Under SAR 10,000", "SAR 10,000–30,000", "SAR 30,000–75,000", "Over SAR 75,000", "Not decided yet"],
    message: "How can we help?",
    messagePh: "Describe your goal or the challenge you’re facing",
    consent: "I agree to my data being processed to answer my request, as described in the",
    consentLink: "privacy policy",
    submit: "Send request",
    sending: "Sending…",
    select: "Select",
    errors: {
      required: "This field is required.",
      email: "Enter a valid email address, like name@company.com.",
      mobile: "Enter a Saudi mobile number: 10 digits starting with 05, or in +9665 format.",
      consent: "Please accept the privacy policy to send your request.",
      summary: "Check the highlighted fields and send again.",
    },
    success: "We’ve received your request and will be in touch soon.",
    mailto: "We opened your email app with the message ready. Send it from there to reach us.",
    failed: "We couldn’t send your request. Try again, or contact us directly.",
    notConnected: "The form isn’t connected to an inbox yet. For now, please use the contact details.",
    subject: "New request from the website",
  },

  shared: {
    stats: [
      { value: "+150", label: "Brands", text: "Whose presence and marketing we’ve managed across government, education and private sectors." },
      { value: "+20", label: "Years of experience", text: "The board’s accumulated management and leadership experience." },
      { value: "4", label: "Arab markets", text: "Saudi Arabia, Egypt, the UAE and Iraq." },
    ],
    sectorsLabel: "Sectors we’ve served:",
    sectorTags: ["Government", "Education", "Media", "Healthcare", "Retail", "Technology"],

    approach: {
      overline: "HOW WE WORK",
      title: "How we work",
      lead: "Five clear stages that make sure every step builds on the one before it.",
      steps: [
        { title: "Analyze", text: "We understand your goal, current situation and audience, and pinpoint the gap between where you are and where you want to be." },
        { title: "Design", text: "We define the scope, plan, budget and KPIs, and agree on them with you." },
        { title: "Execute", text: "We run the service as an extension of your team, with clear responsibilities and timelines." },
        { title: "Measure", text: "We track KPIs and deliver regular reports that show the real impact." },
        { title: "Optimize", text: "We continuously improve performance based on results and data." },
      ],
    },

    why: {
      overline: "WHY AMPLIQ",
      title: "Why us?",
      items: [
        { icon: "award", title: "Proven expertise", text: "More than 150 brands across government, education and private sectors, in 4 Arab markets." },
        { icon: "play-circle", title: "From plan to execution", text: "We don’t just hand over reports — we take part in execution and own the results." },
        { icon: "database", title: "Data-driven decisions", text: "Every activity is tied to KPIs and clear reports that leadership can follow." },
        { icon: "layers", title: "One partner, many functions", text: "Marketing, HR and development under one management and one unified vision." },
        { icon: "map-pin", title: "Deep knowledge of the Saudi market", text: "Familiarity with local regulations, culture and consumer behavior in the Kingdom." },
        { icon: "refresh-cw", title: "Flexible engagement", text: "Working models that fit your size and budget, and scale as you grow." },
      ],
    },

    challenges: {
      overline: "CHALLENGES WE SOLVE",
      title: "Challenges we solve",
      lead: "We start from the client’s real problem — not from an off-the-shelf list of services.",
      items: [
        { icon: "bar-chart-2", title: "Marketing without clear impact", text: "Ad spend and campaigns that aren’t tied to KPIs or to sales results." },
        { icon: "monitor", title: "A digital presence that doesn’t represent you", text: "An outdated, slow or missing website that doesn’t reflect your value or turn visitors into customers." },
        { icon: "shuffle", title: "Fragmented vendors", text: "Separate providers for marketing, hiring and development, with no unified vision." },
        { icon: "users", title: "Hard-to-reach talent", text: "Slow, costly hiring, and teams whose skills don’t match what the stage requires." },
        { icon: "alert-triangle", title: "Lack of structure", text: "Relying on improvisation instead of clear structures, policies and procedures." },
        { icon: "activity", title: "Growth that outpaces readiness", text: "Expansion strains the team and operations before they’re ready." },
      ],
    },

    models: {
      overline: "ENGAGEMENT MODELS",
      title: "Engagement models",
      lead: "Flexible models that fit your organization’s size, stage and budget.",
      items: [
        { icon: "refresh-cw", title: "Monthly retainer", text: "A complete team working as an extension of yours, with a fixed monthly scope and deliverables.", fit: "Organizations that need ongoing marketing and operations." },
        { icon: "grid", title: "Defined project", text: "A clear scope, timeline and deliverables, handed over in full.", fit: "Building websites, restructuring and drafting regulations." },
        { icon: "trending-up", title: "Marketing campaign", text: "Planning and running a campaign with a specific goal and a known budget.", fit: "Seasons, launches and special offers." },
        { icon: "tool", title: "Support & maintenance", text: "A technical support contract with regular updates for your website or platform after launch.", fit: "Existing websites, stores and systems." },
      ],
    },

    sectors: {
      overline: "SECTORS WE SERVE",
      title: "Sectors we serve",
      lead: "Experience built across diverse sectors — each with its own needs, audiences and regulations.",
      items: [
        { icon: "briefcase", title: "Government entities", text: "Awareness campaigns, digital presence management, and support for launching initiatives and programs." },
        { icon: "book-open", title: "Education & training", text: "Marketing academic and training programs, and attracting students and trainees." },
        { icon: "monitor", title: "Media & content", text: "Content strategy, platform management, and growing audiences and engagement." },
        { icon: "heart", title: "Healthcare", text: "Building trust, medical services campaigns, and online reputation management." },
        { icon: "shopping-bag", title: "Retail & e-commerce", text: "Performance, seasonal and promotional campaigns that lift sales and conversions." },
        { icon: "cpu", title: "Technology & startups", text: "Product launches, market positioning, and building growth teams." },
      ],
    },
  },

  services: [
    {
      slug: "digital-marketing",
      icon: "trending-up",
      overline: "DIGITAL MARKETING",
      title: "Digital marketing",
      short: "We create demand in the market and turn marketing spend into results.",
      points: ["Marketing strategy", "Brand management", "Paid advertising campaigns", "Content & platform management", "Performance measurement & reporting"],
      meta: {
        title: "Digital Marketing | Ampliq",
        description: "Marketing strategy, brand management, paid campaigns, content and performance reporting that ties every advertising riyal to a result. Digital marketing by Ampliq, Riyadh.",
      },
      lead: "From visibility to growth: we plan, execute and measure — and tie every advertising riyal to a result.",
      overview: [
        "We create demand in the market and turn marketing spend into results. We start by analyzing the market, audience and competitors, build a marketing plan tied to your business goals, deliver it through content and paid campaigns, and measure every activity against clear KPIs.",
        "We’ve managed the presence and marketing of more than 150 brands across government, education and private sectors, in 4 Arab markets.",
      ],
      offer: {
        title: "What we offer",
        items: [
          { icon: "target", title: "Marketing strategy", text: "Market, audience and competitor analysis, and annual and quarterly marketing plans tied to business goals." },
          { icon: "award", title: "Brand management", text: "Clear positioning, marketing messages and a consistent identity across every customer touchpoint." },
          { icon: "volume-2", title: "Paid advertising campaigns", text: "Planning and managing campaigns across social media and search engines, optimized daily to lower costs." },
          { icon: "edit-3", title: "Content & platform management", text: "Monthly content plans, creative copywriting, design and visual production, and account and community management." },
          { icon: "calendar", title: "Seasonal campaigns & launches", text: "Ramadan, Saudi National Day, seasonal peaks, and launches of new products and services." },
          { icon: "pie-chart", title: "Performance measurement & reporting", text: "Dashboards and regular reports that link spend to results, with clear recommendations for improvement." },
        ],
      },
      results: {
        title: "What do you get?",
        lead: "Clear deliverables, and KPIs we track and report on regularly.",
        outputsTitle: "Deliverables",
        outputs: [
          "An approved marketing plan with clear goals and budget",
          "A monthly content calendar and ready-to-publish designs",
          "Paid campaigns, managed and continuously optimized",
          "A monthly performance report and a live dashboard",
          "Regular review meetings and improvement recommendations",
          "A competitor and audience analysis file",
        ],
        metricsTitle: "KPIs we track",
        metrics: ["Reach & impressions", "Engagement rate", "Cost per lead", "Customer acquisition cost", "Conversion rate", "Return on ad spend", "Follower growth", "Sales & revenue"],
      },
      faq: [
        { q: "Can I engage you for digital marketing only?", a: "Yes. Each of our three services can be engaged on its own or as a package, and we choose the right model with you: a monthly retainer, a marketing campaign, or a defined project." },
        { q: "How do you measure campaign results?", a: "We agree on KPIs with you from the start — such as cost per lead, conversion rate and return on ad spend — and track them through a live dashboard and a monthly performance report." },
        { q: "Do you handle content and design too?", a: "Yes. We prepare a monthly content plan, write the copy, produce the designs and visuals, and manage your accounts and community." },
        { q: "Do you run seasonal campaigns such as Ramadan and National Day?", a: "Yes. We plan and run seasonal campaigns and product or service launches, and you can engage us for these as a standalone campaign with a set goal and budget." },
        { q: "What do I receive each month?", a: "A monthly performance report, a live dashboard, and a regular review meeting with clear recommendations for improvement." },
      ],
    },
    {
      slug: "human-resources",
      icon: "users",
      overline: "HUMAN RESOURCES",
      title: "Human resources management",
      short: "We build teams, organize the workplace and ensure regulatory compliance.",
      points: ["Org structures & job descriptions", "Talent acquisition & recruitment", "Policies & regulations", "Performance management & development", "Saudization & compliance"],
      meta: {
        title: "Human Resources Management | Ampliq",
        description: "Org structures, job descriptions, recruitment, work regulations aligned with the Saudi Labor Law, performance management and Saudization. HR management by Ampliq.",
      },
      lead: "A specialized practice that helps organizations build strong teams, organize the workplace and stay compliant — from setup to development.",
      overview: [
        "We build teams, organize the workplace and ensure regulatory compliance. We start with the org structure and job descriptions, then build recruitment, policies and performance management, and track HR indicators with regular reports.",
        "We believe an organization doesn’t have to build every function in-house from day one. That’s why we work as an extension of your team — at a flexible cost, with measurable results.",
      ],
      offer: {
        title: "What we offer",
        items: [
          { icon: "grid", title: "Organizational structures", text: "Designing the structure, departments and lines of authority to suit the organization’s size." },
          { icon: "file-text", title: "Job descriptions", text: "A card for every role that defines its tasks, qualifications and KPIs." },
          { icon: "search", title: "Talent acquisition & recruitment", text: "Defining needs, advertising, screening and interviewing — all the way to hiring." },
          { icon: "book-open", title: "Policies & regulations", text: "Work regulations and internal policies in line with the Saudi Labor Law." },
          { icon: "target", title: "Performance management", text: "Individual KPIs, appraisal cycles and clear improvement plans." },
          { icon: "dollar-sign", title: "Salary scales & benefits", text: "Structuring pay, allowances and incentives fairly and competitively." },
          { icon: "trending-up", title: "Training & development", text: "Training needs analysis and employee development plans." },
          { icon: "shield", title: "Saudization & compliance", text: "Supporting Saudization requirements and compliance with the relevant regulations." },
        ],
      },
      results: {
        title: "What do you get?",
        lead: "Clear deliverables, and KPIs we track and report on regularly.",
        outputsTitle: "Deliverables",
        outputs: [
          "An approved org structure and authority matrix",
          "A job description manual covering every role",
          "Work regulations and internal policies",
          "A performance appraisal system with ready-to-use forms",
          "A clear salary, benefits and incentives scale",
          "A regular report on HR indicators",
        ],
        metricsTitle: "KPIs we track",
        metrics: ["Time to fill", "Cost per hire", "Employee turnover rate", "Saudization rate", "Employee satisfaction", "Performance goal achievement", "Training hours", "Regulatory compliance"],
      },
      faq: [
        { q: "Do you help new organizations set up HR from scratch?", a: "Yes. We start with the org structure, job descriptions and policies, then build recruitment and performance management — from setup to development." },
        { q: "Are the regulations you prepare aligned with the Saudi Labor Law?", a: "We prepare work regulations and internal policies in line with the Saudi Labor Law, and support Saudization requirements and compliance with the relevant regulations." },
        { q: "Can you handle recruitment on our behalf?", a: "Yes. We define the need, advertise the role, screen applicants and run interviews — all the way to hiring." },
        { q: "How do you measure the impact of your work?", a: "We track indicators such as time to fill, cost per hire, employee turnover and Saudization rate, and report on them regularly." },
        { q: "Can we engage you for a single task, such as a salary scale?", a: "Yes, through the defined project model: a clear scope, timeline and deliverables, handed over in full." },
      ],
    },
    {
      slug: "web-development",
      icon: "code",
      overline: "WEB & SOFTWARE DEVELOPMENT",
      title: "Web & software development",
      short: "We build fast, secure websites and platforms that serve your business goals.",
      points: ["Corporate websites", "E-commerce stores", "Campaign landing pages", "Systems & dashboards", "Hosting, support & maintenance"],
      meta: {
        title: "Web & Software Development | Ampliq",
        description: "Bilingual corporate websites, e-commerce stores, landing pages, custom systems and dashboards, plus hosting and support after launch. Web development by Ampliq.",
      },
      lead: "We build fast, secure websites and digital platforms that reflect your identity and turn visitors into customers.",
      overview: [
        "We build fast, secure websites and platforms that serve your business goals. We design and approve the interfaces before writing code, then build a mobile-friendly site in Arabic and English, connect it to payments and analytics, and train your team to run it.",
        "Because we also do marketing, we build every page to support your campaigns and to be measurable from day one.",
      ],
      offer: {
        title: "What we offer",
        items: [
          { icon: "layout", title: "Corporate websites", text: "Professional Arabic and English websites that present your services and build trust with your customers." },
          { icon: "shopping-cart", title: "E-commerce stores", text: "Complete stores with payment gateways, shipping, and product and order management." },
          { icon: "target", title: "Campaign landing pages", text: "Fast pages designed to convert, connected to analytics tools and ad campaigns." },
          { icon: "server", title: "Systems & dashboards", text: "Custom web systems for managing customers, orders and internal operations." },
          { icon: "pen-tool", title: "UX & UI design", text: "Prototypes and clear interface designs before development starts." },
          { icon: "tool", title: "Hosting, support & maintenance", text: "Reliable hosting, regular updates, backups and technical support after launch." },
        ],
      },
      results: {
        title: "What do you get?",
        lead: "Clear deliverables, and standards we commit to on every project.",
        outputsTitle: "Deliverables",
        outputs: [
          "Approved interface designs before development starts",
          "A mobile-friendly website in Arabic and English",
          "An easy-to-use dashboard for managing content",
          "Payment and analytics integrations",
          "Training for your team on running the site",
          "A warranty and technical support after launch",
        ],
        metricsTitle: "Standards we commit to",
        metrics: ["Loading speed", "Mobile compatibility", "Right-to-left Arabic support", "Search engine optimization", "Security & SSL certificate", "Ease of use", "Scalability", "Analytics integration"],
      },
      faq: [
        { q: "Do you build websites in Arabic and English?", a: "Yes. We build mobile-friendly websites in both languages, with full right-to-left support for Arabic." },
        { q: "Can I edit the website content myself?", a: "Yes. We hand over an easy-to-use dashboard for managing content, and train your team to run the site." },
        { q: "Do you connect stores to payment and shipping providers?", a: "Yes. We build complete stores with payment gateways, shipping, and product and order management." },
        { q: "Will the website be optimized for search engines?", a: "Yes. On every project we commit to search engine optimization, loading speed, mobile compatibility and analytics integration." },
        { q: "What happens after launch?", a: "We provide a warranty and technical support after launch, and you can sign up for support & maintenance: reliable hosting, regular updates and backups." },
      ],
    },
  ],

  pages: {
    home: {
      meta: {
        title: "Ampliq | Amplify Your Business Impact",
        description: "Ampliq is a Riyadh-based growth partner for digital marketing, human resources management, and web & software development — turning expertise and data into measurable results.",
      },
      hero: {
        overline: "AMPLIFY YOUR BUSINESS IMPACT",
        title: "We amplify your business impact, intelligently",
        rotatorPrefix: "Your growth partner in",
        rotator: ["digital marketing", "human resources", "web development"],
        lead: "We turn expertise and data into measurable results, and work as an extension of your team from strategy to execution.",
      },
      clients: { label: "Organizations that trusted our expertise" },
      services: {
        overline: "OUR SERVICES",
        title: "Three tracks under one roof",
        lead: "Engage them individually or as a single package.",
        all: "All services",
      },
      about: {
        overline: "ABOUT AMPLIQ",
        title: "A growth partner bringing marketing, HR and technology together under one roof",
        text: "We work as an extension of our clients’ teams across government entities, educational institutions and private companies. We start by understanding where you are today, then build the strategy, deliver it and measure its impact — turning goals into tangible results.",
        link: "Get to know us",
      },
      blog: { overline: "INSIGHTS", title: "From the blog" },
      start: {
        overline: "LET'S TALK",
        title: "Let’s create a bigger impact together",
        lead: "Tell us about your goal, and we’ll suggest the right track and engagement model for your organization.",
      },
    },

    about: {
      meta: {
        title: "About | Ampliq",
        description: "Ampliq is a Riyadh-based Saudi group bringing digital marketing, HR management, and web & software development under one roof. Our vision, mission and values.",
      },
      hero: {
        overline: "ABOUT AMPLIQ",
        title: "About us",
        lead: "A growth partner bringing marketing, HR and technology together under one roof.",
      },
      story: {
        title: "We turn goals into tangible results",
        paragraphs: [
          "Ampliq is a Saudi group headquartered in Riyadh, specializing in digital marketing, human resources management, and web & software development.",
          "We work as an extension of our clients’ teams across government entities, educational institutions and private companies. We start by understanding where you are today, then build the strategy, deliver it and measure its impact — turning goals into tangible results.",
          "We believe an organization doesn’t have to build every function in-house from day one. That’s why we provide a complete team of experts — at a flexible cost, with measurable results.",
        ],
        pillars: [
          { icon: "trending-up", title: "Digital marketing", text: "We create demand and drive growth" },
          { icon: "users", title: "Human resources", text: "We build teams and organize the workplace" },
          { icon: "code", title: "Web & software development", text: "We build your digital presence" },
        ],
      },
      vision: {
        overline: "VISION & MISSION",
        title: "Our vision & mission",
        visionTitle: "Our vision",
        vision: "To be the smartest growth partner for organizations in Saudi Arabia, through marketing, management and technology solutions that create measurable impact and support Vision 2030’s goals of empowering the private sector and raising institutional efficiency.",
        missionTitle: "Our mission",
        mission: "We deliver integrated marketing, human resources, and web & software development services that combine hands-on expertise, data and technology — raising our clients’ efficiency, accelerating their growth, and relieving them of the burden of building every function in-house.",
      },
      name: {
        overline: "THE NAME",
        title: "The meaning of our name",
        parts: [
          { term: "AMPLIFY", label: "Amplification", text: "We extend reach and raise impact." },
          { term: "IQ", label: "Intelligence", text: "Decisions grounded in data." },
        ],
      },
      values: {
        overline: "OUR VALUES",
        title: "Our values",
        lead: "The principles that govern how we work with every client.",
        items: [
          { icon: "target", en: "IMPACT", title: "Impact", text: "Our success is measured by what our clients achieve, not by how much we deliver." },
          { icon: "zap", en: "INNOVATION", title: "Innovation", text: "Digital solutions and modern tools that scale as our clients grow." },
          { icon: "check-circle", en: "COMMITMENT", title: "Commitment", text: "Continuous follow-up, respect for deadlines, and ownership of results." },
          { icon: "eye", en: "TRANSPARENCY", title: "Transparency", text: "Scope, cost and KPIs that are clear from day one." },
          { icon: "award", en: "PROFESSIONALISM", title: "Professionalism", text: "Structured delivery and clear quality standards worthy of our clients’ trust." },
        ],
      },
      numbers: { overline: "AMPLIQ IN NUMBERS", title: "Experience measured by results" },
    },

    services: {
      meta: {
        title: "Services | Ampliq",
        description: "Digital marketing, human resources management, and web & software development: three integrated tracks you can engage individually or as a package, with flexible engagement models.",
      },
      hero: {
        overline: "OUR SERVICES",
        title: "Our services",
        lead: "Three integrated tracks you can engage individually or as a single package.",
      },
    },

    clients: {
      meta: {
        title: "Clients & Sectors | Ampliq",
        description: "Government, education and media organizations and leading companies that trusted Ampliq’s expertise, across government, education, media, healthcare, retail and technology.",
      },
      hero: {
        overline: "OUR CLIENTS",
        title: "Clients & sectors",
        lead: "We’re proud of the trust of government, education and media organizations and leading companies.",
      },
      logos: { title: "Organizations that trusted our expertise" },
      numbers: { overline: "AMPLIQ IN NUMBERS", title: "Experience measured by results" },
    },

    blog: {
      meta: {
        title: "Blog | Ampliq",
        description: "Practical articles on digital marketing, human resources management and building websites, from the Ampliq team.",
      },
      hero: {
        overline: "INSIGHTS",
        title: "Blog",
        lead: "Practical ideas on marketing, HR and websites, from the Ampliq team.",
      },
      all: "All",
      filterLabel: "Filter by category",
      searchLabel: "Search articles",
      searchPh: "Search…",
      empty: "No matching articles. Try another word or show all categories.",
    },

    contact: {
      meta: {
        title: "Contact | Ampliq",
        description: "Contact Ampliq in Riyadh: tell us about your digital marketing, HR or website goal, and we’ll suggest the right track and engagement model.",
      },
      hero: {
        overline: "CONTACT",
        title: "Contact us",
        lead: "Tell us about your goal, and we’ll suggest the right track and engagement model for your organization.",
      },
      infoTitle: "Contact details",
    },

    privacy: {
      meta: {
        title: "Privacy Policy | Ampliq",
        description: "How Ampliq collects, uses and protects personal data through this website, and your rights under Saudi Arabia’s Personal Data Protection Law.",
      },
      hero: { overline: "PRIVACY POLICY", title: "Privacy policy" },
      updated: "2026-10-09",
      blocks: [
        { type: "p", text: "This policy explains how Ampliq (“we”) collects personal data through this website, how we use and protect it, and the rights you have under Saudi Arabia’s Personal Data Protection Law (PDPL) and its implementing regulations." },
        { type: "h2", text: "Data we collect" },
        { type: "ul", items: [
          "Data you send through the contact form: your name, mobile number, email, organization, service of interest, approximate budget and message.",
          "Technical data our hosting provider logs automatically for security and operations, such as IP address, browser type and time of visit.",
          "Traffic measurement data — only if we enable analytics and you accept them through the cookie banner.",
        ] },
        { type: "h2", text: "How we use data" },
        { type: "ul", items: [
          "To answer your request and contact you about it.",
          "To prepare an offer or proposal that fits your needs.",
          "To improve the website and understand its use in aggregate, with your consent.",
        ] },
        { type: "p", text: "We don’t use your data for marketing without your consent, and we never sell it." },
        { type: "h2", text: "Legal basis for processing" },
        { type: "p", text: "We process your data based on your consent when you submit the form or accept cookies, and only as far as needed to fulfil your request." },
        { type: "h2", text: "Sharing data" },
        { type: "p", text: "We only share your data with service providers we rely on to run the website and receive requests, such as hosting and email — and only as far as necessary — or when required by law." },
        { type: "h2", text: "Retention" },
        { type: "p", text: "We keep data for as long as needed to answer your request and manage our relationship with you, then delete or anonymize it, unless a regulation requires us to keep it longer." },
        { type: "h2", text: "Your rights" },
        { type: "ul", items: [
          "To be informed about how your data is collected and used.",
          "To access your data and obtain a copy of it.",
          "To request correction or updating of your data.",
          "To request destruction of your data when it’s no longer needed.",
          "To withdraw your consent at any time.",
        ] },
        { type: "p", text: "To exercise any of these rights, email us at the address shown on the contact page." },
        { type: "h2", text: "Cookies" },
        { type: "p", text: "The website doesn’t use advertising cookies. If we enable traffic analytics, they only run after you accept them through the banner at the bottom of the page, and declining doesn’t affect your browsing." },
        { type: "h2", text: "Protecting data" },
        { type: "p", text: "We use an encrypted connection (HTTPS) and limit access to data to the people who need it for their work." },
        { type: "h2", text: "Changes to this policy" },
        { type: "p", text: "We may update this policy from time to time, and show the date of the latest update at the top of the page." },
      ],
    },

    terms: {
      meta: {
        title: "Terms of Use | Ampliq",
        description: "Terms of use for the Ampliq website: content ownership, limitation of liability, external links and governing law.",
      },
      hero: { overline: "TERMS OF USE", title: "Terms of use" },
      updated: "2026-10-09",
      blocks: [
        { type: "p", text: "By using this website you agree to the following terms. If you don’t agree, please don’t use the website." },
        { type: "h2", text: "Content and ownership" },
        { type: "p", text: "The text, designs, logo and visual identity on this website belong to Ampliq and may not be copied or republished for commercial purposes without written permission. Client logos belong to their owners and are shown to reference our past experience." },
        { type: "h2", text: "Using the website" },
        { type: "ul", items: [
          "Use the website for lawful purposes only.",
          "Don’t attempt to harm or disrupt the website or gain unauthorized access to its systems.",
          "Provide accurate information when using the contact form.",
        ] },
        { type: "h2", text: "Limitation of liability" },
        { type: "p", text: "Website content is provided for general information. It isn’t a binding offer or professional advice. Any work together is governed by a separate contract that sets out the scope and deliverables." },
        { type: "h2", text: "External links" },
        { type: "p", text: "The website may link to other websites whose content we don’t control, and we aren’t responsible for their practices." },
        { type: "h2", text: "Governing law" },
        { type: "p", text: "These terms are governed by the laws in force in the Kingdom of Saudi Arabia." },
        { type: "h2", text: "Changes" },
        { type: "p", text: "We may change these terms from time to time; changes take effect from the date they’re published on this page." },
      ],
    },

    notFound: {
      title: "Page not found",
      text: "The page may have moved or its link may have changed.",
      home: "Back to home",
    },
  },
};
