// Arabic interface for the Decap CMS dashboard + small RTL fixes.
// Loaded right after decap-cms.js, before the CMS starts (on DOMContentLoaded).
(function () {
  var CMS = window.CMS;
  if (!CMS) return;

  var ar = {
    auth: {
      login: "تسجيل الدخول",
      loggingIn: "جارٍ تسجيل الدخول…",
      loginWithGitHub: "الدخول بحساب GitHub",
    },
    app: {
      header: { content: "المحتوى", workflow: "سير العمل", media: "الصور والملفات", quickAdd: "إضافة سريعة" },
      app: {
        errorHeader: "تعذّر تحميل إعدادات لوحة التحكم",
        configErrors: "أخطاء الإعدادات",
        checkConfigYml: "راجع ملف config.yml.",
        loadingConfig: "جارٍ تحميل الإعدادات…",
        waitingBackend: "جارٍ الاتصال…",
      },
      notFoundPage: { header: "غير موجود" },
    },
    collection: {
      sidebar: { collections: "الأقسام", allCollections: "كل الأقسام", searchAll: "ابحث في الكل", searchIn: "ابحث في" },
      collectionTop: {
        sortBy: "ترتيب حسب",
        viewAs: "طريقة العرض",
        viewAsList: "عرض كقائمة",
        viewAsGrid: "عرض كشبكة",
        newButton: "＋ %{collectionLabel} جديد",
        newButtonAriaLabel: "إضافة %{collectionLabel}",
        ascending: "تصاعدي",
        descending: "تنازلي",
        searchResults: "نتائج البحث عن \"%{searchTerm}\"",
        searchResultsInCollection: "نتائج البحث عن \"%{searchTerm}\" في %{collection}",
        filterBy: "تصفية حسب",
        groupBy: "تجميع حسب",
      },
      entries: {
        loadingEntries: "جارٍ التحميل…",
        cachingEntries: "جارٍ التحميل…",
        longerLoading: "قد يستغرق ذلك بضع دقائق",
        noEntries: "لا توجد عناصر",
        unpublishedHeader: "غير منشور",
      },
      groups: { other: "أخرى", negateLabel: "ليس %{label}" },
      defaultFields: { author: { label: "الكاتب" }, updatedOn: { label: "آخر تعديل" } },
    },
    editor: {
      editorControl: { field: { optional: "اختياري", widgetLabel: "حقل %{widgetLabel}" } },
      editorControlPane: {
        widget: {
          required: "حقل «%{fieldLabel}» مطلوب.",
          regexPattern: "قيمة «%{fieldLabel}» غير صحيحة: %{pattern}",
          processing: "جارٍ معالجة «%{fieldLabel}».",
          range: "يجب أن تكون قيمة «%{fieldLabel}» بين %{minValue} و %{maxValue}.",
          min: "يجب ألا تقل قيمة «%{fieldLabel}» عن %{minValue}.",
          max: "يجب ألا تزيد قيمة «%{fieldLabel}» عن %{maxValue}.",
          rangeCount: "يجب أن يحتوي «%{fieldLabel}» على %{minCount} إلى %{maxCount} عنصر.",
          rangeCountExact: "يجب أن يحتوي «%{fieldLabel}» على %{count} عنصر بالضبط.",
          rangeMin: "يجب أن يحتوي «%{fieldLabel}» على %{minCount} عنصر على الأقل.",
          rangeMax: "يجب ألا يزيد «%{fieldLabel}» عن %{maxCount} عنصر.",
          invalidPath: "المسار '%{path}' غير صحيح",
          pathExists: "المسار '%{path}' موجود مسبقاً",
        },
        i18n: {
          writingInLocale: "الكتابة بـ %{locale}",
          copyFromLocale: "انسخ من اللغة الأخرى",
          copyFromLocaleConfirm: "هل تريد نسخ المحتوى من %{locale}؟\nسيُستبدل كل المحتوى الحالي.",
        },
      },
      editor: {
        onLeavePage: "هل تريد مغادرة الصفحة؟ لن تُحفظ التغييرات.",
        onUpdatingWithUnsavedChanges: "لديك تغييرات غير محفوظة، احفظها أولاً.",
        onPublishingNotReady: "غيّر الحالة إلى «جاهز» قبل النشر.",
        onPublishingWithUnsavedChanges: "لديك تغييرات غير محفوظة، احفظها قبل النشر.",
        onPublishing: "هل تريد النشر؟",
        onUnpublishing: "هل تريد إلغاء النشر؟",
        onDeleteWithUnsavedChanges: "هل تريد حذف هذا العنصر المنشور مع التغييرات غير المحفوظة؟",
        onDeletePublishedEntry: "هل تريد حذف هذا العنصر نهائياً من الموقع؟",
        onDeleteUnpublishedChangesWithUnsavedChanges: "سيتم حذف كل التغييرات غير المنشورة وغير المحفوظة. هل تريد المتابعة؟",
        onDeleteUnpublishedChanges: "سيتم حذف كل التغييرات غير المنشورة. هل تريد المتابعة؟",
        loadingEntry: "جارٍ التحميل…",
        confirmLoadBackup: "وُجدت نسخة محفوظة محلياً لم تُنشر من هذا العنصر. هل تريد استعادتها؟",
      },
      editorInterface: {
        toggleI18n: "إظهار/إخفاء اللغة الثانية",
        togglePreview: "إظهار/إخفاء المعاينة",
        toggleScrollSync: "مزامنة التمرير",
        toggleNotes: "الملاحظات",
      },
      editorToolbar: {
        publishing: "جارٍ النشر…",
        publish: "نشر",
        published: "منشور",
        unpublish: "إلغاء النشر",
        duplicate: "نسخ",
        unpublishing: "جارٍ إلغاء النشر…",
        publishAndCreateNew: "نشر وإضافة جديد",
        publishAndDuplicate: "نشر ونسخ",
        deleteUnpublishedChanges: "حذف التغييرات غير المنشورة",
        deleteUnpublishedEntry: "حذف العنصر غير المنشور",
        deletePublishedEntry: "حذف العنصر",
        deleteEntry: "حذف",
        saving: "جارٍ الحفظ…",
        save: "حفظ",
        deleting: "جارٍ الحذف…",
        updating: "جارٍ التحديث…",
        status: "الحالة: %{status}",
        backCollection: " %{collectionLabel}",
        unsavedChanges: "تغييرات غير محفوظة",
        changesSaved: "تم الحفظ",
        draft: "مسودة",
        inReview: "قيد المراجعة",
        ready: "جاهز",
        publishNow: "انشر الآن",
        deployPreviewPendingButtonLabel: "التحقق من المعاينة",
        deployPreviewButtonLabel: "معاينة",
        deployButtonLabel: "عرض على الموقع",
      },
      editorWidgets: {
        markdown: {
          bold: "عريض",
          italic: "مائل",
          strikethrough: "يتوسطه خط",
          code: "كود",
          link: "رابط",
          linkPrompt: "أدخل الرابط",
          headings: "العناوين",
          quote: "اقتباس",
          bulletedList: "قائمة نقطية",
          numberedList: "قائمة مرقّمة",
          addComponent: "إدراج",
          richText: "محرر",
          markdown: "Markdown",
          toggleMode: { rich: "التبديل إلى المحرر", markdown: "التبديل إلى Markdown" },
        },
        image: {
          choose: "اختر صورة",
          chooseMultiple: "اختر صوراً",
          chooseUrl: "إدراج من رابط",
          replaceUrl: "استبدال برابط",
          promptUrl: "أدخل رابط الصورة",
          chooseDifferent: "اختر صورة أخرى",
          addMore: "أضف صوراً",
          remove: "إزالة الصورة",
          removeAll: "إزالة كل الصور",
        },
        file: {
          choose: "اختر ملفاً",
          chooseUrl: "إدراج من رابط",
          chooseMultiple: "اختر ملفات",
          replaceUrl: "استبدال برابط",
          promptUrl: "أدخل رابط الملف",
          chooseDifferent: "اختر ملفاً آخر",
          addMore: "أضف ملفات",
          remove: "إزالة الملف",
          removeAll: "إزالة كل الملفات",
        },
        headingOptions: {
          headingOne: "عنوان 1",
          headingTwo: "عنوان رئيسي",
          headingThree: "عنوان فرعي",
          headingFour: "عنوان 4",
          headingFive: "عنوان 5",
          headingSix: "عنوان 6",
        },
        datetime: { now: "الآن", clear: "مسح", setToNow: "اليوم" },
        list: { add: "إضافة %{item}", addType: "إضافة %{item}" },
        object: { expand: "توسيع", collapse: "طي" },
      },
    },
    mediaLibrary: {
      mediaLibraryCard: { draft: "مسودة", copy: "نسخ", copyUrl: "نسخ الرابط", copyPath: "نسخ المسار", copyName: "نسخ الاسم", copied: "تم النسخ" },
      mediaLibrary: {
        onDelete: "هل تريد حذف الملفات المحددة؟",
        fileTooLarge: "الملف كبير جداً.\nالحد الأقصى %{size} كيلوبايت.",
      },
      mediaLibraryModal: {
        loading: "جارٍ التحميل…",
        close: "إغلاق",
        noResults: "لا توجد نتائج.",
        noAssetsFound: "لا توجد ملفات.",
        noImagesFound: "لا توجد صور.",
        private: "خاص ",
        images: "الصور",
        mediaAssets: "الملفات",
        search: "بحث…",
        uploading: "جارٍ الرفع…",
        upload: "رفع صورة",
        download: "تنزيل",
        deleting: "جارٍ الحذف…",
        deleteSelected: "حذف المحدد",
        chooseSelected: "اختيار المحدد",
      },
    },
    ui: {
      default: { goBackToSite: "العودة إلى الموقع" },
      errorBoundary: {
        title: "خطأ",
        details: "حدث خطأ — ",
        reportIt: "أبلغ عنه على GitHub.",
        detailsHeading: "التفاصيل",
        recoveredEntry: {
          heading: "المحتوى المستعاد",
          warning: "انسخ هذا المحتوى واحفظه قبل مغادرة الصفحة!",
          copyButtonLabel: "نسخ",
        },
      },
      settingsDropdown: { logOut: "تسجيل الخروج", account: "خيارات الحساب" },
      toast: {
        onFailToLoadEntries: "تعذّر التحميل: %{details}",
        onFailToLoadDeployPreview: "تعذّر تحميل المعاينة: %{details}",
        onFailToPersist: "تعذّر الحفظ: %{details}",
        onFailToDelete: "تعذّر الحذف: %{details}",
        onFailToUpdateStatus: "تعذّر تحديث الحالة: %{details}",
        missingRequiredField: "يوجد حقل مطلوب فارغ. أكمله ثم احفظ.",
        entrySaved: "تم الحفظ — سيظهر التعديل على الموقع خلال دقيقة أو دقيقتين",
        entryPublished: "تم النشر — سيظهر على الموقع خلال دقيقة أو دقيقتين",
        entryUnpublished: "تم إلغاء النشر",
        onFailToPublishEntry: "تعذّر النشر: %{details}",
        onFailToUnpublishEntry: "تعذّر إلغاء النشر: %{details}",
        entryUpdated: "تم تحديث الحالة",
        onDeleteUnpublishedChanges: "تم حذف التغييرات غير المنشورة",
        onFailToAuth: "%{details}",
        onLoggedOut: "انتهت الجلسة. انسخ أي محتوى غير محفوظ ثم سجّل الدخول مرة أخرى.",
        onBackendDown: "خدمة الحفظ متوقفة مؤقتاً. التفاصيل: %{details}",
      },
    },
  };

  var isObj = function (v) { return v && typeof v === "object" && !Array.isArray(v); };
  var merge = function (base, over) {
    var out = {};
    Object.keys(base || {}).forEach(function (k) { out[k] = base[k]; });
    Object.keys(over).forEach(function (k) { out[k] = isObj(over[k]) && isObj(out[k]) ? merge(out[k], over[k]) : over[k]; });
    return out;
  };
  // Missing phrases fall back to English.
  CMS.registerLocale("ar", merge(CMS.getLocale("en"), ar));
})();
